[project]
name = "taller-llm-modulo1"
version = "0.1.0"
description = "Base de Conocimiento Semántica y Sistema Q&A para Dollarcity"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # --- CORE IA & LANGCHAIN ---
    "langchain>=0.3.0",
    "langchain-community>=0.3.0",
    "langchain-ollama>=0.2.0",
    # --- VECTOR DB & EMBEDDINGS ---
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    # --- WEB API (Para conectar con React) ---
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "pydantic>=2.9.0",
    # --- SCRAPING & DATA ---
    "crawl4ai>=0.4.0",
    "beautifulsoup4>=4.12.3",
    "playwright>=1.47.0",
    "pandas>=2.2.0",
    "pymupdf>=1.24.0",
    # --- UTILS ---
    "python-dotenv>=1.0.1",
    "requests>=2.32.0",
    "aiohttp>=3.10.0",
    "httpx>=0.27.0",
    "sympy>=1.14.0",
    "langchainhub>=0.1.21",
]

[dependency-groups]
dev = []

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
